### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by Mystic135** [DankMemer/CommunityBot#6]
Hi, I am Mystic from the dmc server in discord. While switching between the channels when it was locked for the bot dank being down, I happened to click on the profile of the community bot, and in its about info I found the link of this repo, and so came and saw that the code is 'open_source'. So how will I use the code? Like, the config, esp. the bot token and stuff yea? (Since there's no direction written in the readme)

**Comment by Fellintron** [comment]
> Hi, I am Mystic from the dmc server in discord. While switching between the channels when it was locked for the bot dank being down, I happened to click on the profile of the community bot, and in its about info I found the link of this repo, and so came and saw that the code is 'open_source'. So how will I use the code? Like, the config, esp. the bot token and stuff yea? (Since there's no direction written in the readme)

I mean- if you are a programmer I'm pretty sure you can easily use the code for your own bot and config and bot tokens- would be private ofc, this code would be really helpful for your upcoming d.js projects. it's also public for another reason, for users to watch and learn..

**Comment by Dauntless7** [comment]
Hey, this code was never meant to be used in other servers as it's tailored specifically for DMC. The readme was never officially done but I'll get to that soon. If you'd like to host it locally or test out the commands/features, you'd need to:

- install [mongo](https://www.mongodb.com/try/download/community)
- create a bot application [here](https://discord.com/developers/applications) and copy the bot token
- `git pull https://github.com/DankMemer/CommunityBot.git` in your terminal
- `cd CommunityBot/src`
- `npm i`
- fill out `secrets.json` and `config.json` with the appropriate IDs etc., both example files are in `configs` folder
- `node .` 

You should see something like this once the bot booted properly:
![image](https://user-images.githubusercontent.com/47513707/149664810-b21b7913-ac8f-4498-a2c3-eec34e8e88d5.png)
