### ISSUE TITLE
can't find secrets.json and unable to make my own

### ISSUE THREAD

**Issue by GameWax** [DankMemer/CommunityBot#9]
i am unable to find the secrets.json file in configs folder, i tried making my own but it won't work, here is what i put: 

{
"botToken": "my bot token"
"mongo": "my mongo url"
}

could someone please help?

**Comment by malosaa** [comment]
> i am unable to find the secrets.json file in configs folder, i tried making my own but it won't work, here is what i put:
> 
> { "botToken": "my bot token" "mongo": "my mongo url" }
> 
> could someone please help?

{
"botToken": "my bot token",
"mongo": "my mongo url"
}

u forget the ","
